name: llama-cpp-python-server
services:
  llama-cpp-python-server:
    build:
      args:
        - USER_UID=${USER_UID:?USER_UID not set}
        - USER_GID=${USER_GID:?USER_GID not set}
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
    env_file:
      - ${SECRETS_ENV:-.secrets.env}
    environment:
      - USER_UID=${USER_UID:?USER_UID not set}
      - USER_GID=${USER_GID:?USER_GID not set}
    image: llama-cpp-python-server
    ports:
      - ${PORT:-8000}:8000
    volumes:
      - ${CONFIG_PATH:-./data/config}:/app/data/config
      - ${MODELS_PATH:-./data/models}:/app/data/models
      - read_only: true
        source: ${SECRETS_PATH:-./secrets}
        target: /run/secrets
        type: bind
    command: "poetry run python main.py"
