name: dev-llama-cpp-python-server
services:
  dev-llama-cpp-python-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              count: 1
              driver: nvidia
    image: dev-llama-cpp-python-server
    ports:
      - 9369:8000
    volumes:
      - ${MODELS_PATH:-~/data/llm_models}:/app/data/models
      - ${CONFIG_PATH:-./config/config.json}:/app/config/config.json
      - ${LOGS_PATH:-./data/logs}:/app/data/logs
